#!/bin/sh

# FasterEdgeOS 系统初始化序列：
#
# /init (本文件)
#  |
#  +--(1) /etc/01_prepare.sh
#  |
#  +--(2) /etc/02_overlay.sh
#          |
#          +-- /etc/03_init.sh
#               |
#               +-- /sbin/init
#                    |
#                    +--(1) /etc/04_bootscript.sh
#                    |       |
#                    |       +-- /etc/autorun/* (所有脚本)
#                    |
#                    +--(2) /bin/sh (Alt + F1, 主控制台)
#                    |
#                    +--(2) /bin/sh (Alt + F2)
#                    |
#                    +--(2) /bin/sh (Alt + F3)
#                    |
#                    +--(2) /bin/sh (Alt + F4)

echo -e "欢迎使用 FasterEdgeOS (/init)"

# 挂载所有核心文件系统。
/etc/01_prepare.sh

# 打印第一段提示。
cat /etc/msg/init_01.txt

# 等待 5 秒或任一按键。
read -t 5 -n1 -s key

if [ ! "$key" = "" ] ; then
  # 打印第二段提示。
  cat /etc/msg/init_02.txt

  # 设置标志，表示已获得控制终端。
  export PID1_SHELL=true

  # 以 PID 1 交互式 Shell 运行（带控制终端）。
  exec setsid cttyhack sh
fi

# 在内存中创建新的挂载点，将其作为新的根目录，并与存储区域（如果存在
# overlay 区域）做 overlay 合并。该操作会把脚本 '/etc/03_init.sh' 作为新的
# init 进程调用。
exec /etc/02_overlay.sh

echo "(/init) - 除非存在严重错误，否则你不应看到此行。"

# 等待按键。
read -n1 -s